name: Trigger Actions from Form

on:
  workflow_dispatch:
  repository_dispatch:
    types: [form-submission]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Actions from Form
        run: echo "Name ${{ github.event.client_payload.name }} submitted from Pages"
